#!/bin/bash
LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
echo $LOGNOW
cd /osrm/
if [ -f download.lock1 ];
  then
    echo "An downloading is already in progress. Aborting..."
    exit 1
fi

touch download.lock1
echo "Downloading latest planet OSM..."
#wget -O planet-latest-updated.pbf http://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-latest.osm.pbf
osmupdate planet-latest.osm.pbf planet-latest-updated.pbf --day -v

touch download.lock0

mv planet-latest-updated.pbf planet-latest.osm.pbf
rm list.old

echo "Complete..."
rm download.lock0
rm download.lock1

LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
echo $LOGNOW