#!/bin/bash
#LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
#echo $LOGNOW
cd /osrm/
if [ -f download.lock0 ];
  then
    #echo "An download is in progress. Aborting..."
    exit 1
fi

if [ -f region.lock ];
  then
    #echo "An region update is in progress. Aborting..."
    exit 1
fi

#echo $LOGNOW
touch region.lock

#echo "Getting updated region list..."
wget -O list.new --header="Authorization: Basic YTFhZGE1YWItYjhjMi0xMWU1LTg0N2QtMDBmZmQwZWE5MjcyOkgzbHBOMHcyMDE2" http://HelpNowLB-1559668033.ap-northeast-1.elb.amazonaws.com/api/eventlocation/boundingbox/list

if grep -q Bounds list.new;
then
    :
    #echo "New bounds downloaded"
else
    rm region.lock
    exit 1
fi

if cmp -s list.new list.old
then
    :
    #echo "No region updates to perform. Operation Complete."
else
    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Region Update Required. Starting update..."

    REGIONCNT=0

    while read BBOX
    do
        if [ "$BBOX" != "Bounds" ]
        then
            /usr/local/bin/osmconvert planet-latest.osm.pbf -b="$BBOX" -o="region$REGIONCNT.o5m" -v &
            MERGEARGS[$REGIONCNT]="region$REGIONCNT.o5m"
            REGIONCNT=$((REGIONCNT+1))
        fi
    done < list.new

    wait

    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Event regions extracted from planet-wide data. Compressing to single data set."

    touch region.lock1

    /usr/local/bin/osmconvert "${MERGEARGS[@]}" -o=region.osm.pbf -v
    rm -rf "${MERGEARGS[@]}"
    mv list.new list.old
    touch blocked_nodes.update

    rm region.lock1

    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Region Update Complete"
fi

rm region.lock

