#!/bin/bash
LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
echo $LOGNOW

cd /osrm
if [ -f update.lock ];
  then
    echo "An update is already in progress. Aborting..."
    exit 1
fi

if [ -f region.lock1 ];
  then
    echo "The region PBF is currently being updated. Aborting..."
    exit 1
fi

touch update.lock

if [ -f blocked_nodes.update ];
  then
    rm blocked_nodes.update
    rm blocked_nodes.lua
fi

echo "Getting updated blocked nodes..."
wget -O blocked_nodes.new --header="Authorization: Basic BACKENDKEY" http://www.helpnowmap.com/api/blockage/routes/nodes

if cmp -s blocked_nodes.new blocked_nodes.lua
then
    echo "No blocked nodes to update. Operation complete."
else
    echo "Performing blocked node updates..."

    mv blocked_nodes.new blocked_nodes.lua

    /usr/local/bin/osrm-extract region.osm.pbf
    /usr/local/bin/osrm-contract region.osrm
    /usr/local/bin/osrm-datastore region.osrm

    rm update.lock
    echo "Complete!"
fi

rm update.lock

LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
echo $LOGNOW
