#!/bin/bash
#LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
#echo $LOGNOW

cd /osrm
if [ -f update.lock ];
  then
    #echo "An update is already in progress. Aborting..."
    exit 1
fi

if [ -f region.lock1 ];
  then
    #echo "The region PBF is currently being updated. Aborting..."
    exit 1
fi

touch update.lock

if [ -f blocked_nodes.update ];
  then
    rm blocked_nodes.update
    rm blocked_nodes.lua
fi

#echo "Getting updated blocked nodes..."
wget -O blocked_nodes.new --header="Authorization: Basic YTFhZGE1YWItYjhjMi0xMWU1LTg0N2QtMDBmZmQwZWE5MjcyOkgzbHBOMHcyMDE2" http://www.helpnowmap.com/api/blockage/routes/nodes

if cmp -s blocked_nodes.new blocked_nodes.lua
then
    :
    #echo "No blocked nodes to update. Operation complete."
else
    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Starting path extraction with blocked nodes"

    mv blocked_nodes.new blocked_nodes.lua

    /usr/local/bin/osrm-extract region.osm.pbf

    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Contracting region paths"

    /usr/local/bin/osrm-contract region.osrm
    /usr/local/bin/osrm-datastore region.osrm

    rm update.lock
    LOGNOW="$(TZ=US/Mountain date +%m/%d/%y\ %H:%M:%S)"
    echo "$LOGNOW - Routing updated and live!"
fi

rm update.lock
